### ISSUE TITLE
Natural Language Tools

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#65]
# WP 1.5

- ML-enabled EaaS. Main tasks: adapt CRIM’s existing NLU implementations; 
- create domain-specific ontologies; 
- develop tools for metadata annotation of workflows; 
- develop query expansion strategies; 
- adapt matching algorithms; 
- develop a query understanding​ ​ interface.

## User story
Beginner user wants to know what the risks for heatwaves will be in 2040 in Montreal. On the site search bar, user types "heatwave risks Montreal 2040". The expected output for the search are in order of pertinence: a graphic showing the projected frequency of heatwaves in Montreal, a GIS layer showing heatwave or annual maximum temperature future maps including Montreal, workflows to compute heatwaves from climate simulations, data storing heatwave variables. 

The search engine can search through the WPS registry to look for processes related to heat, heat stress, heatwaves or maximum temperature. It can then look into workflows using these processes, and outputs generated through these processes, ranking the results in terms of their coverage of the region and period of interest. 

## Todo 
- [ ] Make list of climate related ontologies
- [ ] Make list of EO related ontologies
- [ ] Add keywords to existing WPS processes that respect the ontologies (semantic description of process?)
- [ ] Semantic translation of workflows

## References
 - [Geospatial Semantic Web Interoperability Experiment](http://www.opengeospatial.org/projects/initiatives/gswie)

**Comment by huard** [comment]
To be moved to DACCS repo.
